services:
  javaclient:
    image: up-mqtt-java-demo:latest
    ports:
      - "8080:8080"
    depends_on:
      - mqttbroker
    healthcheck:
      test: "curl http://127.0.0.1:8080"
      interval: 30s
      timeout: 30s
      start_period: 120s
      retries: 6

  mqttbroker:
    image: eclipse-mosquitto:latest
    ports:
      - "8883:1883"
      - "9001:9001"
    volumes:
      - ./src/main/resources/mosquitto:/mosquitto/config:ro
    healthcheck:
      test: "curl -f http://localhost:1883"
      interval: 5s
      timeout: 5s
      start_period: 20s
      retries: 3
